on:
  workflow_call:
    inputs:
      script_name_with_args:
        required: true
        type: string

jobs:
  run_script_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python -m pip install --upgrade pip wheel
      - name: Install deps
        run: python -m pip install -r requirements.txt
      - name: Install package
        run: python -m pip install -e .
      - name: Run script from update-web-metadata repo
        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          python ${{ inputs.script_name_with_args }}
